//
//  OrderListModel.swift
//  QSC_SwiftUI
//
//  Created by FIT on 11/08/2025.
//

import Foundation


struct OrderListRequestModel: Codable {
    
}

struct OrderListResponseModel:Codable {
    var AccountID: String? = ""
    var AccountNameA: String? = ""
    var AccountNameE: String? = ""
    var AvgExePrice: String? = ""
    var ClientID: String? = ""
    var CompanyShortNameA: String? = ""
    var CompanyShortNameE: String? = ""
    var EntryDate: String? = ""
    var Exchange: String? = ""
    var ExecOrderComm: String? = ""
    var ExecQty: String? = ""
    var MaxPrice: String? = ""
    var MinFillQty: String? = ""
    var MinPrice: String? = ""
    var ModifyDate: String? = ""
    var NIN: String? = ""
    var OrdComm: String? = ""
    var OrderID: String? = ""
    var OrderValue: String? = ""
    var OrderTypeCode: String? = ""
    var OriginCode: String? = ""
    var Precision: String? = ""
    var Price: String? = ""
    var RejectReason: String? = ""
    var Remaining: String? = ""
    var Remark: String? = ""
    var SMART_ORDER_ID: String? = ""
    var SellBuyFlag: String? = ""
    var StatusCode: String? = ""
    var StopLossPx: String? = ""
    var Symbol: String? = ""
    var TotalVolume: String? = ""
    var ValidityCode: String? = ""
    var ValidityDate: String? = ""
    var VisibleQty: String? = ""
    var BANK_ACCOUNT_NO: String? = ""
    var SmartOrderID: String? = ""
    var Sett_Type: String? = ""
    var CustodianID: String? = ""
    var cur_Code: String? = ""
    var TrxnID: String? = ""
    var SymbolCode: String? = ""
    var BookCode: String? = ""
    var BrokerID: String? = ""
    var SourceCode: String? = ""
    var UserID: String? = ""
    var OrigUserID: String? = ""
    var MarketTypeCode: String? = ""
    var Source2Code: String? = ""
    var ProcSentFlag: String? = ""
    var MarketOrderID: String? = ""
    var IntOrderID: String? = ""
    var MsgCode: String? = ""
    var SenderSubID: String? = ""
    var BuyerMember: String? = ""
    var SellerMember: String? = ""
    var IsinCode: String? = ""
    var FIXOrderID: String? = ""
    var TP_price: String? = ""
    var SL_price: String? = ""
    var TR_price: String? = ""
    var Max_TR_price: String? = ""
    var TR_Price_is_perc: String? = ""
    var BE_Price: String? = ""
    var SPL_Order_flag: String? = ""
    var ApprovalStatusCode: String? = ""
    var ApprovalTypeCode: String? = ""
    var SenderCompanyID: String? = ""
    var LocalValue: String? = ""
    var SymbolLongName: String? = ""
    var B_OutOfMarketType: String? = ""
    var B_OutOfMarketDate: String? = ""
    var B_GroupName: String? = ""
    var IP_Address: String? = ""
    var LastUpdateTime: String? = ""
    var SmartOrderTypeDesc_E: String? = ""
    var SmartOrderTypeDesc_A: String? = ""
    var SymbolNameE: String? = ""
    var SymbolNameA: String? = ""
}

struct OrderListUIModel: Codable{
    var AccountID: String? = ""
    var AccountNameA: String? = ""
    var AccountNameE: String? = ""
    var AvgExePrice: String? = ""
    var ClientID: String? = ""
    var CompanyShortNameA: String? = ""
    var CompanyShortNameE: String? = ""
    var EntryDate: String? = ""
    var Exchange: String? = ""
    var ExecOrderComm: String? = ""
    var ExecQty: String? = ""
    var MaxPrice: String? = ""
    var MinFillQty: String? = ""
    var MinPrice: String? = ""
    var ModifyDate: String? = ""
    var NIN: String? = ""
    var OrdComm: String? = ""
    var OrderID: String? = ""
    var OrderValue: String? = ""
    var OrderTypeCode: String? = ""
    var OriginCode: String? = ""
    var Precision: String? = ""
    var Price: String? = ""
    var RejectReason: String? = ""
    var Remaining: String? = ""
    var Remark: String? = ""
    var SMART_ORDER_ID: String? = ""
    var SellBuyFlag: String? = ""
    var StatusCode: String? = ""
    var StopLossPx: String? = ""
    var Symbol: String? = ""
    var TotalVolume: String? = ""
    var ValidityCode: String? = ""
    var ValidityDate: String? = ""
    var VisibleQty: String? = ""
    var BANK_ACCOUNT_NO: String? = ""
    var SmartOrderID: String? = ""
    var Sett_type: String? = ""
    var CustodianID: String? = ""
    var cur_Code: String? = ""
    var TrxnID: String? = ""
    var SymbolCode: String? = ""
    var BookCode: String? = ""
    var BrokerID: String? = ""
    var SourceCode: String? = ""
    var UserID: String? = ""
    var OrigUserID: String? = ""
    var MarketTypeCode: String? = ""
    var Source2Code: String? = ""
    var ProcSentFlag: String? = ""
    var MarketOrderID: String? = ""
    var IntOrderID: String? = ""
    var MsgCode: String? = ""
    var SenderSubID: String? = ""
    var BuyerMember: String? = ""
    var SellerMember: String? = ""
    var IsinCode: String? = ""
    var FIXOrderID: String? = ""
    var TP_price: String? = ""
    var SL_price: String? = ""
    var TR_price: String? = ""
    var Max_TR_price: String? = ""
    var TR_Price_is_perc: String? = ""
    var BE_Price: String? = ""
    var SPL_Order_flag: String? = ""
    var ApprovalStatusCode: String? = ""
    var ApprovalTypeCode: String? = ""
    var SenderCompanyID: String? = ""
    var LocalValue: String? = ""
    var SymbolLongName: String? = ""
    var B_OutOfMarketType: String? = ""
    var B_OutOfMarketDate: String? = ""
    var B_GroupName: String? = ""
    var IP_Address: String? = ""
    var LastUpdateTime: String? = ""
    var SmartOrderTypeDesc_E: String? = ""
    var SmartOrderTypeDesc_A: String? = ""
    var SymbolNameE: String? = ""
    var SymbolNameA: String? = ""
}

extension OrderListUIModel{
    static func mapToUIModel(_ m:OrderListResponseModel) -> Self? {
        return OrderListUIModel(AccountID: m.AccountID ?? "", AccountNameA: m.AccountNameA ?? "", AccountNameE: m.AccountNameE ?? "", AvgExePrice: m.AvgExePrice ?? "", ClientID: m.ClientID ?? "", CompanyShortNameA: m.CompanyShortNameA ?? "", CompanyShortNameE: m.CompanyShortNameE ?? "", EntryDate: m.EntryDate ?? "", Exchange: m.Exchange ?? "", ExecOrderComm: m.ExecOrderComm ?? "", ExecQty: m.ExecQty ?? "", MaxPrice: m.MaxPrice ?? "", MinFillQty: m.MinFillQty ?? "", MinPrice: m.MinPrice ?? "", ModifyDate: m.ModifyDate ?? "", NIN: m.NIN ?? "", OrdComm: m.OrdComm ?? "", OrderID: m.OrderID ?? "", OrderValue: m.OrderValue ?? "", OrderTypeCode: m.OrderTypeCode ?? "", OriginCode: m.OriginCode ?? "", Precision: m.Precision ?? "", Price: m.Price ?? "", RejectReason: m.RejectReason ?? "", Remaining: m.Remaining ?? "", Remark: m.Remark ?? "", SMART_ORDER_ID: m.SMART_ORDER_ID ?? "", SellBuyFlag: m.SellBuyFlag ?? "", StatusCode: m.StatusCode ?? "", StopLossPx: m.StopLossPx ?? "", Symbol: m.Symbol ?? "", TotalVolume: m.TotalVolume ?? "", ValidityCode: m.ValidityCode ?? "", ValidityDate: m.ValidityDate ?? "", VisibleQty: m.VisibleQty ?? "", BANK_ACCOUNT_NO: m.BANK_ACCOUNT_NO ?? "", SmartOrderID: m.SmartOrderID ?? "", Sett_type: m.Sett_Type ?? "", CustodianID: m.CustodianID ?? "", cur_Code: m.cur_Code ?? "", TrxnID: m.TrxnID ?? "", SymbolCode: m.SymbolCode ?? "", BookCode: m.BookCode ?? "", BrokerID: m.BrokerID ?? "", SourceCode: m.SourceCode ?? "", UserID: m.UserID ?? "", OrigUserID: m.OrigUserID ?? "", MarketTypeCode: m.MarketTypeCode ?? "", Source2Code: m.Source2Code ?? "", ProcSentFlag: m.ProcSentFlag ?? "", MarketOrderID: m.MarketOrderID ?? "", IntOrderID: m.IntOrderID ?? "", MsgCode: m.MsgCode ?? "", SenderSubID: m.SenderSubID ?? "", BuyerMember: m.BuyerMember ?? "", SellerMember: m.SellerMember ?? "", IsinCode: m.IsinCode ?? "", FIXOrderID: m.FIXOrderID ?? "", TP_price: m.TP_price ?? "", SL_price: m.SL_price ?? "", TR_price: m.TR_price ?? "", Max_TR_price: m.Max_TR_price ?? "", TR_Price_is_perc: m.TR_Price_is_perc ?? "", BE_Price: m.BE_Price ?? "", SPL_Order_flag: m.SPL_Order_flag ?? "", ApprovalStatusCode: m.ApprovalStatusCode ?? "", ApprovalTypeCode: m.ApprovalTypeCode ?? "", SenderCompanyID: m.SenderCompanyID ?? "", LocalValue: m.LocalValue ?? "", SymbolLongName: m.SymbolLongName ?? "", B_OutOfMarketType: m.B_OutOfMarketType ?? "", B_OutOfMarketDate: m.B_OutOfMarketDate ?? "", B_GroupName: m.B_GroupName ?? "", IP_Address: m.IP_Address ?? "", LastUpdateTime: m.LastUpdateTime ?? "", SmartOrderTypeDesc_E: m.SmartOrderTypeDesc_E ?? "", SmartOrderTypeDesc_A: m.SmartOrderTypeDesc_A ?? "", SymbolNameE: m.SymbolNameE ?? "", SymbolNameA: m.SymbolNameA ?? "")
    }
    static func initializer() -> Self {
        return OrderListUIModel()
    }
}
