//
//  SendAddOrderRequest.swift
//  QSC
//
//  Created by FIT on 27/10/2024.
//  Copyright © 2024 FIT. All rights reserved.
//

import Foundation

struct SendAddOrderRequestRequestModel {
    var username: String?
    var hubAddModifyOrder: RequestOrderHubItem?
    var typeAdd: String?
}

struct SendAddOrderRequestResponseModel: Codable {
    var accountID: String? = ""
    var accountNameA: String? = ""
    var accountNameE: String? = ""
    var avgExePrice: String? = ""
    var clientID: String? = ""
    var companyShortNameA: String? = ""
    var companyShortNameE: String? = ""
    var entryDate: String? = ""
    var exchange: String? = ""
    var execOrderComm: String? = ""
    var execQty: String? = ""
    var maxPrice: String? = ""
    var minFillQty: String? = ""
    var minPrice: String? = ""
    var modifyDate: String? = ""
    var nin: String? = ""
    var ordComm: String? = ""
    var orderID: String? = ""
    var orderValue: String? = ""
    var OrderTypeCode: String? = ""
    var originCode: String? = ""
    var precision: String? = ""
    var price: String? = ""
    var rejectReason: String? = ""
    var remaining: String? = ""
    var remark: String? = ""
    var smartorderid: String? = ""
    var sellBuyFlag: String? = ""
    var statusCode: String? = ""
    var stopLossPx: String? = ""
    var symbol: String? = ""
    var totalVolume: String? = ""
    var validityCode: String? = ""
    var validityDate: String? = ""
    var visibleQty: String? = ""
    var bANKACCOUNTNO: String? = ""
    var smartOrderID: String? = ""
    var settType: String? = ""
    var custodianID: String? = ""
    var curCode: String? = ""
    var TrxnID: String? = ""
    var symbolCode: String? = ""
    var bookCode: String? = ""
    var brokerID: String? = ""
    var sourceCode: String? = ""
    var userID: String? = ""
    var origUserID: String? = ""
    var marketTypeCode: String? = ""
    var source2Code: String? = ""
    var procSentFlag: String? = ""
    var marketOrderID: String? = ""
    var intOrderID: String? = ""
    var msgCode: String? = ""
    var senderSubID: String? = ""
    var buyerMember: String? = ""
    var sellerMember: String? = ""
    var isinCode: String? = ""
    var fIXOrderID: String? = ""
    var tPPrice: String? = ""
    var sLPrice: String? = ""
    var tRPrice: String? = ""
    var maxTRPrice: String? = ""
    var tRPriceIsPerc: String? = ""
    var bEPrice: String? = ""
    var sPLOrderFlag: String? = ""
    var approvalStatusCode: String? = ""
    var approvalTypeCode: String? = ""
    var senderCompanyID: String? = ""
    var localValue: String? = ""
    var symbolLongName: String? = ""
    var bOutOfMarketType: String? = ""
    var bOutOfMarketDate: String? = ""
    var bGroupName: String? = ""
    var iPAddress: String? = ""
    var lastUpdateTime: String? = ""
    var SmartOrderTypeDesc_E: String? = ""
    var SmartOrderTypeDesc_A: String? = ""
}
