//
//  SendOrdersModel.swift
//  QSC
//
//  Created by FIT on 24/10/2024.
//  Copyright © 2024 FIT. All rights reserved.
//

import Foundation

struct SendOrdersRequestModel: Codable {
    var clientID, webUserID, exchange, symbol, orderID, sellBuyFlag: String?
}

struct SendOrdersResponseModel:Codable {
    var AccountID: String? = ""
    var AccountNameA: String? = ""
    var AccountNameE: String? = ""
    var AvgExePrice: String? = ""
    var ClientID: String? = ""
    var CompanyShortNameA: String? = ""
    var CompanyShortNameE: String? = ""
    var EntryDate: String? = ""
    var Exchange: String? = ""
    var ExecOrderComm: String? = ""
    var ExecQty: String? = ""
    var MaxPrice: String? = ""
    var MinFillQty: String? = ""
    var MinPrice: String? = ""
    var ModifyDate: String? = ""
    var NIN: String? = ""
    var OrdComm: String? = ""
    var OrderID: String? = ""
    var OrderValue: String? = ""
    var OrderTypeCode: String? = ""
    var OriginCode: String? = ""
    var Precision: String? = ""
    var Price: String? = ""
    var RejectReason: String? = ""
    var Remaining: String? = ""
    var Remark: String? = ""
    var SMART_ORDER_ID: String? = ""
    var SellBuyFlag: String? = ""
    var StatusCode: String? = ""
    var StopLossPx: String? = ""
    var Symbol: String? = ""
    var TotalVolume: String? = ""
    var ValidityCode: String? = ""
    var ValidityDate: String? = ""
    var VisibleQty: String? = ""
    var BANK_ACCOUNT_NO: String? = ""
    var SmartOrderID: String? = ""
    var Sett_Type: String? = ""
    var CustodianID: String? = ""
    var cur_Code: String? = ""
    var TrxnID: String? = ""
    var SymbolCode: String? = ""
    var BookCode: String? = ""
    var BrokerID: String? = ""
    var SourceCode: String? = ""
    var UserID: String? = ""
    var OrigUserID: String? = ""
    var MarketTypeCode: String? = ""
    var Source2Code: String? = ""
    var ProcSentFlag: String? = ""
    var MarketOrderID: String? = ""
    var IntOrderID: String? = ""
    var MsgCode: String? = ""
    var SenderSubID: String? = ""
    var BuyerMember: String? = ""
    var SellerMember: String? = ""
    var IsinCode: String? = ""
    var FIXOrderID: String? = ""
    var TP_price: String? = ""
    var SL_price: String? = ""
    var TR_price: String? = ""
    var Max_TR_price: String? = ""
    var TR_Price_is_perc: String? = ""
    var BE_Price: String? = ""
    var SPL_Order_flag: String? = ""
    var ApprovalStatusCode: String? = ""
    var ApprovalTypeCode: String? = ""
    var SenderCompanyID: String? = ""
    var LocalValue: String? = ""
    var SymbolLongName: String? = ""
    var B_OutOfMarketType: String? = ""
    var B_OutOfMarketDate: String? = ""
    var B_GroupName: String? = ""
    var IP_Address: String? = ""
    var LastUpdateTime: String? = ""
    var SmartOrderTypeDesc_E: String? = ""
    var SmartOrderTypeDesc_A: String? = ""
    var SymbolNameE: String? = ""
    var SymbolNameA: String? = ""
}
